### ISSUE TITLE
[Feature Request] Add a shortcut

### ISSUE THREAD

**Issue by inertia42** [b-yp/logseq-pangu#10]
If I want to format text using this plugin, there are only two ways: using the option from the right-click menu or using a command. Is it possible to register a shortcut for this function?

**Comment by b-yp** [comment]
Of course, I can handle it before tomorrow.

**Comment by b-yp** [comment]
https://github.com/b-yp/logseq-pangu/pull/11#issuecomment-1894344557

Done 😀
